modLoader="javafml"
loaderVersion="[37,)"
license="The Apache License, Version 2.0"
issueTrackerURL="https://github.com/MelanX/Boohoo/issues"

[[mods]]
modId="boohoo"
version="${file.jarVersion}"
displayName="Boohoo!"
displayURL="www.curseforge.com/members/melanx/"
credits="Thanks for my girlfriend Finja1308 for the main idea"
authors="MelanX"
description="""
Adds a spooky ghost woohoo
"""

[[dependencies.boohoo]]
    modId="forge"
    mandatory=true
    versionRange="[37.0.74,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.boohoo]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1, 1.18)"
    ordering="NONE"
    side="BOTH"

[[dependencies.boohoo]]
    modId="libx"
    mandatory=true
    versionRange="[1.17.1-2.1.3,)"
    ordering="NONE"
    side="BOTH"
